
INSERT INTO SOURCE VALUES (1, 'RTI', current_timestamp(), null, null, 'WEB');

INSERT INTO CUSTOMER_INFO VALUES (1, '1234-abc', 'RTI', current_timestamp(), 123, '123-abc-def', null, null, 'HealthX', 'www.healthx.com', '123-abc-456', '123-def-456');

INSERT INTO PORTAL_TYPE VALUES (1, 'RTI', current_timestamp(), null, null, 'MEMBER');

INSERT INTO REQUEST_TYPE VALUES (1, 'RTI', current_timestamp(), null, null, 'NEW_ENROLLMENT',1);


